apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"config.openshift.io/v1","kind":"OAuth","metadata":{"annotations":{"include.release.openshift.io/ibm-cloud-managed":"true","include.release.openshift.io/self-managed-high-availability":"true","include.release.openshift.io/single-node-developer":"true","release.openshift.io/create-only":"true"},"creationTimestamp":"2022-07-28T16:11:32Z","generation":3,"name":"cluster","ownerReferences":[{"apiVersion":"config.openshift.io/v1","kind":"ClusterVersion","name":"version","uid":"fe2b3641-43ba-4e03-8b6b-28a5696a5901"}],"resourceVersion":"124071","uid":"5177eecf-0fcf-48c0-b0cb-e2e3e7bd5f64"},"spec":{"identityProviders":[{"htpasswd":{"fileData":{"name":"clusterusers"}},"mappingMethod":"claim","name":"myusers","type":"HTPasswd"}]}}
    release.openshift.io/create-only: "true"
  creationTimestamp: "2022-07-28T16:11:32Z"
  generation: 4
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: fe2b3641-43ba-4e03-8b6b-28a5696a5901
  resourceVersion: "127834"
  uid: 5177eecf-0fcf-48c0-b0cb-e2e3e7bd5f64
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: localusers
    mappingMethod: claim
    name: myusers
    type: HTPasswd
